name: "Dashy"
landing_name: "DASHY"
repository_uri: "https://github.com/AxelMMalaghan/single-cell-browser"
code_path: ""
entrypoint: "app.py"
env_vars:
  - name: "SC_BROWSER_CONFIG_ROOT"
    value: "/app/config/"
  - name: "SC_BROWSER_DATA_ROOT"
    value: "/app/data/"
data_mounts:
  - host: "/stornext/DataSAN/Bioinformatics/Applications/dashy/config/"
    container: "/app/config/"
  - host: "/stornext/DataSAN/Bioinformatics/Applications/dashy/data/"
    container: "/app/data/"